apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-demo

resources:
  - k8s/app/deployment.yaml
  - k8s/loki/datasource.yaml

# Generate the Grafana dashboard ConfigMap from the JSON file
configMapGenerator:
  - name: grafana-dashboards
    namespace: monitoring
    files:
      - k8s/grafana/dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
